/**
 * 참여자 화면 문구 모음 (PRD §8, §10, §40, §52).
 * 연구 지표·내부 영상코드·가설은 여기에 쓰지 않는다 (check:forbidden 이 검출).
 */
import { formatDurationKo, MAX_RESEARCH_VIDEO_MS } from "@/lib/video-limits";

export const copy = {
  app: {
    title: "영유아 관찰기록 연구",
  },
  enter: {
    title: "연구 참여 접속",
    lead: "안내받으신 참여코드와 PIN을 입력해 주세요.",
    codeLabel: "참여코드",
    codePlaceholder: "예: T07",
    pinLabel: "PIN",
    submit: "접속하기",
    submitting: "확인 중…",
    errors: {
      INVALID_CREDENTIALS: "참여코드 또는 PIN이 올바르지 않습니다. 안내받은 정보를 다시 확인해 주세요.",
      LOCKED_OUT: "여러 번 실패하여 잠시 접속이 제한되었습니다. 15분 뒤에 다시 시도해 주세요.",
      STUDY_INACTIVE: "연구가 현재 진행 중이 아닙니다. 연구자에게 문의해 주세요.",
      PARTICIPANT_BLOCKED: "참여가 종료된 코드입니다. 연구자에게 문의해 주세요.",
      VALIDATION: "참여코드와 PIN 형식을 확인해 주세요.",
      DEFAULT: "접속 중 문제가 발생했습니다. 잠시 후 다시 시도해 주세요.",
    },
    blocked: {
      study_inactive: "연구가 현재 진행 중이 아닙니다. 연구자에게 문의해 주세요.",
      withdrawn: "참여가 종료된 코드입니다. 연구자에게 문의해 주세요.",
      technical_issue: "기술적인 문제로 참여가 잠시 중단되었습니다. 연구자에게 문의해 주세요.",
      session_expired: "접속 시간이 만료되었습니다. 다시 접속하시면 이어서 진행할 수 있습니다.",
    },
  },
  welcome: {
    title: "영유아 관찰기록 연구에 참여해 주셔서 감사합니다.",
    lead: "짧은 영유아 활동영상을 관찰하고 평소 어린이집에서 기록하시는 방식으로 관찰내용을 작성하게 됩니다.",
    bullets: (n: number, minutes: number, totalMinutes: number) => [
      `총 ${n}개의 영상을 관찰합니다.`,
      `각 영상은 ${formatDurationKo(MAX_RESEARCH_VIDEO_MS)} 이내입니다.`,
      `영상 한 편당 최대 ${minutes}분이 주어집니다.`,
      `전체 본 관찰은 최대 약 ${totalMinutes}분입니다.`,
      "정답을 맞히는 시험이 아닙니다.",
      "평소 관찰기록을 작성하듯 자연스럽게 기록해 주세요.",
    ],
    envTitle: "참여 환경",
    env: (audio: boolean) => [
      "PC 또는 노트북",
      "안정적인 인터넷",
      "집중할 수 있는 장소",
      ...(audio ? ["소리를 들을 수 있는 환경"] : []),
    ],
    next: "다음",
    mobileBlocked:
      "이 연구는 PC 또는 노트북에서 참여해 주세요. 관찰기록을 작성하는 시간을 비교하는 연구이기 때문에 휴대폰·태블릿에서는 진행할 수 없습니다. PC에서 같은 링크로 접속하시면 이어서 진행됩니다.",
    mobileWarning: "휴대폰·태블릿에서는 화면이 작아 기록이 불편할 수 있습니다. 가능하면 PC에서 참여해 주세요.",
  },
  consent: {
    title: "연구 참여 및 영상 보안 동의",
    lead: "아래 내용을 읽고 모두 동의하시면 다음으로 진행됩니다.",
    securityTitle: "연구영상 보안 안내",
    securityBody:
      "연구영상에는 실제 어린이집 영유아가 등장합니다. 영상은 연구 참여 화면에서만 재생되며, 어떤 방식으로도 저장·복제·공유하지 않아야 합니다.",
    items: {
      participate: "연구 참여 안내를 읽었으며 연구에 참여하는 것에 동의합니다.",
      no_copy: "연구영상을 저장·녹화·캡처·복제·공유하지 않겠습니다.",
      research_only: "연구목적 외 용도로 영상을 사용하지 않겠습니다.",
    },
    submit: "동의하고 계속하기",
  },
  profile: {
    title: "기본 정보",
    lead: "연구 분석을 위한 기본 정보입니다. 이름 등 개인을 알아볼 수 있는 정보는 수집하지 않습니다.",
    experience: "어린이집 교사 경력",
    years: "년",
    months: "개월",
    ageGroup: "현재 담당 반 연령",
    frequency: "평소 관찰기록 작성 빈도",
    videoExperience: "영상을 보고 관찰기록을 작성해 본 경험",
    aiExperience: "생성형 AI(예: ChatGPT) 사용 경험",
    submit: "저장하고 계속하기",
    select: "선택해 주세요",
    options: {
      ageGroup: {
        age_0: "만 0세",
        age_1: "만 1세",
        age_2: "만 2세",
        age_3: "만 3세",
        age_4: "만 4세",
        age_5: "만 5세",
        mixed: "혼합연령",
        not_homeroom: "현재 담임 아님",
      },
      frequency: {
        daily: "거의 매일",
        several_per_week: "주 2~3회",
        weekly: "주 1회 정도",
        several_per_month: "월 2~3회",
        monthly_or_less: "월 1회 이하",
      },
      videoExperience: {
        none: "없음",
        few_times: "몇 번 해본 적 있음",
        regular: "정기적으로 활용",
      },
      aiExperience: {
        never: "사용해 본 적 없음",
        tried: "한두 번 사용",
        sometimes: "가끔 사용",
        often: "자주 사용",
      },
    },
  },
  guide: {
    title: "관찰 방법 안내",
    steps: [
      "먼저 영상을 처음부터 끝까지 한 번 시청합니다.",
      "첫 시청이 끝나면 관찰기록을 작성합니다.",
      "기록하면서 필요하면 영상을 다시 볼 수 있습니다.",
      "두 번째 시청부터는 일시정지하거나 필요한 장면을 다시 확인할 수 있습니다.",
      "영상에서 실제로 관찰한 내용을 중심으로 평소 관찰기록을 작성하듯 기록해 주세요.",
      "충분히 작성했다고 생각되면 제한시간 이전에도 제출할 수 있습니다.",
    ],
    notes: (minutes: number) => [
      "처음 시청 중에는 영상을 멈추거나 되감을 수 없습니다. 첫 시청이 끝나면 기록창이 열립니다.",
      `제한시간 ${minutes}분은 영상이 처음 재생되는 순간부터 시작됩니다.`,
      "작성 중인 내용은 자동으로 저장됩니다. 제출한 뒤에는 수정할 수 없습니다.",
    ],
    startPractice: "연습 시작하기",
    reopen: "안내 다시 보기",
  },
  practice: {
    banner: "연습 관찰입니다. 이 기록은 연구 자료에 포함되지 않습니다.",
    label: "연습 관찰",
    done: "연습이 끝났습니다. 이제 본 관찰을 시작합니다.",
  },
  hub: {
    title: "본 관찰",
    progress: (done: number, total: number) => `관찰 ${done} / ${total} 완료`,
    ordinal: (n: number) => ["첫", "두", "세", "네", "다섯", "여섯", "일곱", "여덟", "아홉", "열"][n - 1] ?? `${n}`,
    start: (n: number) => `${copy.hub.ordinal(n)} 번째 관찰 시작하기`,
    lead: (total: number) => `총 ${total}개의 영상을 순서대로 관찰합니다.`,
    note: "시작 버튼을 누르면 영상이 준비된 뒤 시청 시작 버튼이 나타납니다. 제한시간은 영상이 재생되는 순간부터 시작됩니다.",
    afterPractice: "연습이 끝났습니다. 이제 본 관찰을 시작합니다.",
    empty: "배정된 관찰이 없습니다. 연구자에게 문의해 주세요.",
  },
  observation: {
    label: (n: number, total: number) => `관찰 ${n} / ${total}`,
    timer: {
      label: "남은 시간",
      oneMinute: "1분 남음",
      thirty: "곧 종료됩니다",
      ten: "자동 제출됩니다",
      expired: "제한시간이 끝났습니다",
    },
    preparing: "영상을 준비하고 있습니다…",
    preloadSlow: "영상 준비가 평소보다 오래 걸리고 있습니다. 네트워크 상태를 확인해 주세요.",
    startWatch: "시청 시작",
    startHint: "시청 시작을 누르면 제한시간이 시작됩니다. 첫 시청 중에는 멈추거나 되감을 수 없습니다.",
    restartTitle: "이전 시청이 중단되었습니다.",
    restartBody: "영상을 처음부터 다시 시청합니다. 남은 시간은 계속 줄어듭니다.",
    restart: "다시 시청하기",
    firstWatching: "첫 시청 중입니다. 시청이 끝나면 기록창이 열립니다.",
    firstWatchDone: "첫 시청이 끝났습니다. 이제 관찰기록을 작성할 수 있습니다.",
    editorLabel: "관찰한 내용을 기록해 주세요.",
    editorLocked: "첫 시청이 끝나면 기록할 수 있습니다.",
    editorPlaceholder: "영상에서 관찰한 내용을 평소 관찰기록을 작성하듯 기록해 주세요.",
    loadingDraft: "기록을 불러오는 중…",
    charCount: (n: number) => `${n}자`,
    submit: "기록 제출하기",
    submitDialogTitle: "기록을 제출할까요?",
    submitDialogBody: "제출한 뒤에는 수정할 수 없습니다.",
    submitDialogEmpty: "아직 작성한 내용이 없습니다. 그래도 제출할까요?",
    submitConfirm: "제출",
    submitCancel: "계속 작성",
    submitting: "제출 중…",
    timeoutTitle: "제한시간이 끝났습니다.",
    timeoutBody: "지금까지 작성한 내용이 자동으로 제출되었습니다.",
    next: "다음으로",
    autosave: {
      idle: "",
      dirty: "작성 중",
      saving: "저장 중…",
      saved: (time: string) => `저장됨 (${time})`,
      error: "저장 실패 — 잠시 후 다시 시도합니다",
      offline: "오프라인 — 연결되면 자동으로 저장됩니다",
    },
    controls: {
      play: "재생",
      pause: "일시정지",
      restart: "처음부터 다시 보기",
      back5: "5초 뒤로",
      forward5: "5초 앞으로",
      mute: "소리 끄기",
      unmute: "소리 켜기",
      fullscreen: "전체화면",
      exitFullscreen: "전체화면 종료",
      slider: "재생 위치",
      time: (cur: string, total: string) => `${cur} / ${total}`,
    },
    mediaError: "영상을 재생할 수 없습니다. 네트워크 상태를 확인한 뒤 다시 시도해 주세요.",
    retry: "다시 시도",
    offline: "네트워크가 잠시 끊겼습니다. 작성 중인 내용은 이 기기에 보관되며, 연결되면 자동으로 저장됩니다.",
    sessionExpired: "접속 시간이 만료되었습니다. 다시 접속하시면 이어서 진행할 수 있습니다.",
    watermark: (code: string) => `연구참여용 ${code}`,
    notExam: "시험이 아닙니다. 평소처럼 기록해 주세요.",
  },
  complete: {
    title: "모든 관찰을 완료했습니다.",
    lines: [
      "연구에 참여해 주셔서 감사합니다.",
      "선생님께서 작성해 주신 관찰기록은 영유아 관찰과 인공지능 기술의 가능성을 연구하기 위한 자료로 활용됩니다.",
      "연구영상과 연구 과정에서 확인한 내용은 외부에 공유하지 말아 주세요.",
      "이제 창을 닫으셔도 됩니다.",
    ],
  },
  common: {
    loading: "불러오는 중…",
    error: "문제가 발생했습니다. 잠시 후 다시 시도해 주세요.",
    skipToMain: "본문으로 건너뛰기",
  },
} as const;
